apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playground

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: paserlab
      app.kubernetes.io/part-of: paserlab
